import type { Metadata } from "next";
import "./globals.css"; 

export const metadata: Metadata = {
  title: "Gagosian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/minion-pro"
          rel="stylesheet"
        ></link>
        <link
          href="https://fonts.cdnfonts.com/css/times-new-roman"
          rel="stylesheet"
        ></link>
      </head>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
